In [1]:
 #we will often import a number of extra packages into python. These are just a the ones we need today:
import math
import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as stats


## Writing Functions:

We have used a lot of prebuilt functions in python all semester. These include things like "print" and "plt.plot" and even "np.log10".
However, we often want to reuse code we've written to do more complicated tasks! This semestser, you've mostly just copied and pasted as needed, which works, and lets us see what we're doing clearly. But it's not the most efficient way to handle this problem. So here, I'll demonstrate how to define your own functions, and how that might be helpful, using our linear regression sample data!

### First example function:

In the block below is a very simple function. "Def" is used to define a function called hello. There is no input to this function, so we include empty parenthesis, and then end with a colon. Anything after the colon which in indented is inside the function (just like a for loop or if/then statement!)

Run the block below and see what happens!

In [2]:
# A simple function

def hello():
    print("hello from inside a function")
    

Huh? Nothing happened. Well, not really - we defined the function. For the rest of this notebook, our code knows a new function called hello that is supposed to print that statement. If we want to use the function, we call it in the code, just like we use any of the built in functions!

Run the block below to actually call the function:

In [3]:
hello()

hello from inside a function


## First useful function

Ok, that's cute, but not terribly useful. Let's build a function for something we actually need more often, like say, calculating an average and a standard deviation!

Note two changes to this compared to the hello function:
1. We are passing some information into the function, and well tell python that by including a variable in parathesis when we define the function!

2. At the end of this function, we also want to return some variables with our numbers saved. The line return allows us to do that!




In [4]:
def xands(data):
    import math
    n = len(data)
    # averaege
    sumdata = 0
    for x in data:
        sumdata = sumdata + x
        
    average = sumdata/n
    
    # standard deviation
    sigma_x = 0
    for x in data:
        sigma_x = sigma_x + ((x-average)**2)
    
    std = math.sqrt(sigma_x/(n-1))
    
    return(average,std)


    

## Calling a Function

Now we call the function, to use it. Note a few handy details!
1. It doesn't matter that the variables names match what we used in the function! Anything we pass into the function in paranethesis gets treated as the variable "data" regardless of what we call it in our code.

2. The same thing is true for the return variables! Althrough in the function, I called them average and std, here, I'm just calling them x and y. It doesn't matter, as long as a remember that averages is returned first, and std is returned second!

In [5]:
sample = [14.1, 11.0, 13.8, 13.6, 14.8] # some old data

x,y = xands(sample) # call the function (sample is going into th efunction, x and y are what are returned)

# check the results - does it look like we got an average and a standard deviation?
print(x) 
print(y)



13.460000000000003
1.4484474446799926


In [6]:
#Now we can reuse that function whenever!

from numpy import random
# generate some random data
x = random.randint(100, size=(3, 5))

print(x) 


# use the function to make iteration easy!

mean = []
stdev = []

for i in range(4):
    av, std = xands(x[:,i])
    mean.append(av)
    stdev.append(std)
    print(F"The average and standard deviation for column number {i} is {av} +/- {std}")
    


#print(mean)
#print(stdev)
    

    

[[11 80 66 90 77]
 [57 20 32 74 14]
 [16 56 41 18 63]]
The average and standard deviation for column number 0 is 28.0 +/- 25.238858928247925
The average and standard deviation for column number 1 is 52.0 +/- 30.199337741083
The average and standard deviation for column number 2 is 46.333333333333336 +/- 17.61628034896508
The average and standard deviation for column number 3 is 60.666666666666664 +/- 37.80652501002087


## Try Building a Function to solve for Response Factor!

Gather your thoughts
1. What information needs to be passed into the function?
2. What information needs to be returned?
3. What calculation do you want to do inside the function? Write out the necessary algebra!

Give it a shot!

In [7]:
# define your function here - 


    
    
    



In [8]:
# use your function here - test it out on our in-class example problem

Ax = 1200 # analyte signal
Ac = 5.0 # analyte concentration
ISx = 2400 # IS signal
ISc = 5.0 # IS concentration

